name: ml-job-scheduler CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/ml-job-scheduler
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        mongodb-version: [ '7.0', '6.0' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - uses: actions/checkout@v4
      - name: Use MongoDB from GitHub Actions
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: pip install -r requirements.txt
      